version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_GOOGLE_DRIVE_FOLDER_ID=${LANGCHAIN_GOOGLE_DRIVE_FOLDER_ID}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/.credentials/keys.json
    ports:
      - "8080:8080"

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    depends_on:
      - api
    ports:
      - "8501:8501"